### PR TITLE
- Added acceptance tests for various supported platforms.

### PR DESCRIPTION
**Pull request by rehanone**

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi!

what's the reason why you support is module so hard?

Cheers,
Jan

**Comment by rehanone** [comment]
@jkroepke simply because I have been using this module for 2 years. As far as I know, this is the only one that supports Archlinux. Is there a problem with my changes?

**Comment by jkroepke** [comment]
> Is there a problem with my changes?

No, no.

I'm just wondering. But hey, I like it that someone is dropping all the old legacy crap. 🎉

**Comment by rehanone** [comment]
@jkroepke Thanks for reviewing and merging my pull requests. This is the last change I wanted to make for now. Feel free to release it at your convenience.

**Pull request merged**
