### PR TITLE
Converted the module to use Puppet Development Kit.

### PR DESCRIPTION
**Pull request by rehanone**
- Converted the module to use Puppet Development Kit.
- Fixed style errors.

### CODE REVIEW

**Comment by jkroepke** [comment]
Wow amazing. Thanks a lot.

**Comment by jkroepke** [comment]
Does PDK generate all the stuff?

**Comment by rehanone** [comment]
@jkroepke Yes, this is all the stuff that PDK generated using its default template. It can be customized using a .sync file but I think for this module it may not be required.

The main thing I am trying to fixing in this module are the validate_* statements that generate a lot of depreciation warnings in the newer versions of puppetlabs-stdlib module. I have added the Puppet types for all the parameters but since the testing of this module was not very consistent I though it might be better to convert it to PDK first.

Please let me know if there are any further questions.

**Comment by jkroepke** [comment]
Impressive.

**Pull request merged**
